# Generated by Django 3.0.4 on 2020-05-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_checkoutdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutDetail',
        ),
    ]
