# Generated by Django 3.0.4 on 2020-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_checkoutdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
