# Generated by Django 3.0.4 on 2020-05-05 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0005_auto_20200504_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breakfast', models.TextField(default=None, max_length=100)),
                ('Dinner', models.TextField(default=None, max_length=100)),
                ('Lunch', models.TextField(default=None, max_length=100)),
                ('datetimenow', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
