# Generated by Django 3.0.4 on 2020-05-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutDetail',
        ),
    ]
