# Generated by Django 3.0.4 on 2020-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBreakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breakfast', models.CharField(default=None, max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuDinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinner', models.CharField(default=None, max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuLunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lunch', models.CharField(default=None, max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonvegBreakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breakfast', models.CharField(default=None, max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonvegDinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinner', models.CharField(default=None, max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonvegLunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lunch', models.CharField(default=None, max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TodaySpecialBreakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breakfast', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TodaySpecialDinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinner', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TodaySpecialLunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lunch', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
