# Generated by Django 3.0.4 on 2020-05-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breakfast', models.CharField(default=None, max_length=100)),
                ('PriceBreakfast', models.IntegerField()),
                ('Lunch', models.CharField(default=None, max_length=100)),
                ('PriceLunch', models.IntegerField()),
                ('Dinner', models.CharField(default=None, max_length=100)),
                ('PriceDinner', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nonveg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breakfast', models.CharField(default=None, max_length=100)),
                ('Lunch', models.CharField(default=None, max_length=100)),
                ('Dinner', models.CharField(default=None, max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TodaySpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breakfast', models.CharField(default=None, max_length=100)),
                ('Lunch', models.CharField(default=None, max_length=100)),
                ('Dinner', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MenuBreakfast',
        ),
        migrations.DeleteModel(
            name='MenuDinner',
        ),
        migrations.DeleteModel(
            name='MenuLunch',
        ),
        migrations.DeleteModel(
            name='NonvegBreakfast',
        ),
        migrations.DeleteModel(
            name='NonvegDinner',
        ),
        migrations.DeleteModel(
            name='NonvegLunch',
        ),
        migrations.DeleteModel(
            name='TodaySpecialBreakfast',
        ),
        migrations.DeleteModel(
            name='TodaySpecialDinner',
        ),
        migrations.DeleteModel(
            name='TodaySpecialLunch',
        ),
    ]
